spring.application.name=backend
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
omdb.api.base-url=https://www.omdbapi.com/
tmdb.api.base-url=https://api.themoviedb.org/
omdb.api.key=${OMDB_API_KEY}
sonar.token=${SONAR_TOKEN}